name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'  
  - title: '📝 Documentation updates'
    label: 'documentation'
  - title: '💥 Breaking changes'
    label: 'breaking'
  # Default label used by Dependabot
  - title: '📦 Dependency updates'
    label: 'dependencies'
  - title: '🎨 UX improvements'
    label: 'ux'
  - title: '🚦 Tests'
    labels: 
      - 'test'
      - 'tests'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
